services:
  xray-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    ports:
      - 2096:2096 # API backend/subs
      - 46156:46156 # VLESS
    restart: unless-stopped
    tty: true
    healthcheck:
      test: "wget --no-verbose --spider --tries=1 http://127.0.0.1:2053 || exit 1"
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
