services:
  xray-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    ports:
      - 2053:2053
      - 28682:28682
      - 14302:14302
    restart: unless-stopped
    tty: true
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
